services:
  - type: web
    name: chess-backend
    env: python
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/server.py"
    envVars:
      - key: SERVER_PORT
        value: ${SERVER_PORT}
      - key: PYTHON_VERSION
        value: "3.9.13"

  - type: web
    name: chess-frontend
    env: static
    buildCommand: "echo 'Building frontend...'"
    staticPublishPath: "./frontend"