-- CREA DATABASE scacchi
CREATE DATABASE scacchi
WITH OWNER = postgres
ENCODING = 'UTF8';

-- TABELLE PER IL GIOCO DEGLI SCACCHI (PostgreSQL)
CREATE TABLE game_state (
    id INT PRIMARY KEY,
    fen TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE moves (
    id SERIAL PRIMARY KEY,
    move_notation VARCHAR(10) NOT NULL,
    fen TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INSERISCI STATO INIZIALE
INSERT INTO game_state (id, fen) VALUES (1, 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')
ON CONFLICT (id) DO UPDATE SET fen = EXCLUDED.fen;

-- ATTENZIONE!! CREARE MANUALMENTE IL RUOLO utente_scacchi, password=password

-- ASSEGNA PRIVILEGI ALL'UTENTE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO utente_scacchi;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO utente_scacchi;
